CREATE TABLE users (id SERIAL PRIMARY KEY, username TEXT, password TEXT);

CREATE TABLE lists (id SERIAL PRIMARY KEY, user_id INTEGER REFERENCES users, name TEXT);

CREATE TABLE tasks (id SERIAL PRIMARY KEY, list_id INTEGER REFERENCES lists, task TEXT, status INTEGER);
