CREATE TABLE users (id SERIAL PRIMARY KEY, username TEXT, password TEXT);

CREATE TABLE lists (id SERIAL PRIMARY KEY, user_id INTEGER REFERENCES users, name TEXT);

CREATE TABLE tasks (id SERIAL PRIMARY KEY, list_id INTEGER REFERENCES lists ON DELETE CASCADE, task TEXT, status INTEGER);

CREATE TABLE notes (id SERIAL PRIMARY KEY, user_id INTEGER REFERENCES users, name TEXT)

CREATE TABLE entrys (id SERIAL PRIMARY KEY, notes_id INTEGER REFERENCES notes ON DELETE CASCADE, entry TEXT, timestamp TEXT)